import { Pi } from "app/mod/pi";
var s,table, min = 99999999, max = 0;
if(!Pi.sample) {
		Pi.sample = {};
	};
    table = Pi.sample;

if(min==0)min = 150001;
if(max==9999999)max = 150001;
s = {};
s.sid=150001;
s.name="心法残页";
s.count=["$var",1];
s.quality=4;
s.drop_location=[[102],[103]];
s.describe="可用于购买珍贵心法！";
s.icon_normal="gest_coin";
s.icon="res_150001";
s.type="gest_coin";
s.folder_pos="Item";
s.drop_module="model_dl_daizi";
s.use_mode = -1;
s.comment="心法代币";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150001] = s;

if(min==0)min = 150002;
if(max==9999999)max = 150002;
s = {};
s.sid=150002;
s.name="灵魂残片";
s.count=["$var",1];
s.quality=4;
s.drop_location=[];
s.describe="可用于神兵铸魂！";
s.icon_normal="treasure_coin";
s.icon="res_150002";
s.type="treasure_coin";
s.folder_pos="Item";
s.drop_module="model_dl_daizi";
s.use_mode = -1;
s.comment="神兵升级材料";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150002] = s;

if(min==0)min = 150003;
if(max==9999999)max = 150003;
s = {};
s.sid=150003;
s.name="星灵";
s.count=["$var",1];
s.quality=5;
s.drop_location=[];
s.describe="可用于激活装备升星的星宿图谱！";
s.icon_normal="weapon_coin";
s.icon="res_150003";
s.type="ep_star_coin";
s.folder_pos="Item";
s.drop_module="model_dl_baoxiang";
s.use_mode = -1;
s.comment="装备升星获得的成就点";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150003] = s;

if(min==0)min = 150004;
if(max==9999999)max = 150004;
s = {};
s.sid=150004;
s.name="战勋";
s.count=["$var",1];
s.quality=4;
s.drop_location=[];
s.describe="可在竞技场商店购买稀缺商品！";
s.icon_normal="jjc_score";
s.icon="res_150004";
s.type="jjc_coin";
s.folder_pos="Item";
s.drop_module="model_dl_baoxiang";
s.use_mode = -1;
s.comment="竞技场商店币";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150004] = s;

if(min==0)min = 150005;
if(max==9999999)max = 150005;
s = {};
s.sid=150005;
s.name="门派贡献";
s.count=["$var",1];
s.quality=4;
s.drop_location=[];
s.describe="可用于购买门派商店的宝物！";
s.icon_normal="guild_score";
s.icon="res_150005";
s.type="menpai_coin";
s.folder_pos="Item";
s.drop_module="model_dl_baoxiang";
s.use_mode = -1;
s.comment="门派贡献";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150005] = s;

if(min==0)min = 150006;
if(max==9999999)max = 150006;
s = {};
s.sid=150006;
s.name="灵宠通宝";
s.count=["$var",1];
s.quality=5;
s.drop_location=[];
s.describe="灵宠外观分解得到的代币，可用于召唤稀有灵宠！";
s.icon_normal="pet_score";
s.icon="res_150006";
s.type="pet_coin";
s.folder_pos="Item";
s.drop_module="model_dl_daizi";
s.use_mode = -1;
s.comment="灵宠分解得到的代币";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150006] = s;

if(min==0)min = 150007;
if(max==9999999)max = 150007;
s = {};
s.sid=150007;
s.name="时装通宝";
s.count=["$var",1];
s.quality=5;
s.drop_location=[];
s.describe="时装分解得到的代币，可用于购买稀有时装！";
s.icon_normal="cloth_score";
s.icon="res_150007";
s.type="cloth_coin";
s.folder_pos="Item";
s.drop_module="model_dl_daizi";
s.use_mode = -1;
s.comment="时装分解得到的代币";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150007] = s;

if(min==0)min = 150008;
if(max==9999999)max = 150008;
s = {};
s.sid=150008;
s.name="积分";
s.count=["$var",1];
s.quality=5;
s.drop_location=[];
s.describe="抽奖获得的积分，可用于积分商店购买！";
s.icon_normal="cloth_score";
s.icon="res_150007";
s.type="draw_coin";
s.folder_pos="Item";
s.drop_module="model_dl_daizi";
s.use_mode = -1;
s.comment="时装分解得到的代币";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150008] = s;

if(min==0)min = 150009;
if(max==9999999)max = 150009;
s = {};
s.sid=150009;
s.name="充值令牌";
s.count=["$var",1];
s.quality=5;
s.drop_location=[];
s.describe="充值获得的代币，可用于抽奖";
s.icon_normal="weapon_coin";
s.icon="res_150007";
s.type="wand_coin";
s.folder_pos="Item";
s.drop_module="model_dl_daizi";
s.use_mode = -1;
s.comment="充值获得的代币";
if(s.sid < min) min = s.sid;
if(s.sid > max) max = s.sid;
table[150009] = s;
