
export const menu_parent = [{
        key:"role",
        icon:"menu_role_icon",
        name:"角色",
        interface:"gotoRole",
        stage_id:"0",
        level_limit:0,tips:["role"]
    },{
        key:"equip_level",
        icon:"menu_equip_icon",
        name:"装备",
        interface:"gotoForge,0",
        stage_id:"2",
        level_limit:0,tips:["equip"]
    },{
        key:"bag",
        icon:"menu_bag_icon",
        name:"背包",
        interface:"gotoBag",
        stage_id:"0",
        level_limit:0,tips:["bag"]
    },{
        key:"gang",
        icon:"pic_gang",
        name:"门派",
        interface:"gotoGang",
        stage_id:"10",
        level_limit:0,tips:["gang"]
    },{
        key:"exp_fb",
        icon:"menu_fb_icon",
        name:"副本",
        interface:"gotoFb",
        stage_id:"5",
        level_limit:0,tips:["explore"]
    },{
        key:"public_boss",
        icon:"menu_explore_icon",
        name:"探索",
        interface:"gotoExplore",
        stage_id:"18",
        level_limit:0,tips:["new_fun"]
    }
]; 