export const playermission_base = {
	dailyFB:{
		"type":0,
		"comment":"参加1次每日副本"
	}
	,ep_diamond:{
		"type":2,
		"comment":"装备宝石总等级达到2级"
	}
	,ep_level:{
		"type":2,
		"comment":"装备强化总等级达到30级"
	}
	,ep_levelup:{
		"type":1,
		"comment":"装备强化1次"
	}
	,ep_star:{
		"type":2,
		"comment":"装备总星级达到2级"
	}
	,gest:{
		"type":0,
		"comment":"激活1个阵法"
	}
	,gestFB:{
		"type":0,
		"comment":"挑战心法副本1次"
	}
	,guild:{
		"type":0,
		"comment":"创建或加入门派"
	}
	,instance:{
		"type":0,
		"comment":"通关九幽幻境第一章第5关，是大于等于5关"
	}
	,jjc_rank:{
		"type":2,
		"comment":"竞技场达到4000名以上"
	}
	,mission:{
		"type":0,
		"comment":"通关装备副本第一章第一关1次，是大于等于1关"
	}
	,mystic_box:{
		"type":0,
		"comment":"开启1次神秘宝箱"
	}
	,reclam:{
		"type":1,
		"comment":"熔炼1件装备"
	}
	,role_level:{
		"type":2,
		"comment":"等级到达2级"
	}
	,skill_level:{
		"type":2,
		"comment":"任意技能达到2级"
	}
	,soul:{
		"type":0,
		"comment":"九窍精魂总等级达到3级"
	}
	,tower_point:{
		"type":2,
		"comment":"天庭秘境达到20层以上"
	}
	,treasure:{
		"type":0,
		"comment":"激活神兵"
	}
	,treasure_phase:{
		"type":2,
		"comment":"神兵进阶至2阶"
	}
	,treasure_skill:{
		"type":1,
		"comment":"释放1次神兵技能"
	}
	,wild_boss:{
		"type":1,
		"comment":"击杀1次野外首领"
	}
	,wild_mission:{
		"type":1,
		"comment":"完成1次修炼任务"
	}
	,wild_randomboss:{
		"type":0,
		"comment":"参与击杀1次宝箱守卫"
	}
	,world_talk:{
		"type":1,
		"comment":"世界频道发言1次"
	}
	,exp_fb:{
		"type":1,
		"comment":"参与经验副本1次"
	}
	,pet_starup:{
		"type":1,
		"comment":"宠物培养2次"
	}
	,red_equip_wash:{
		"type":1,
		"comment":"红装洗练2次"
	}
	,treasure_hexagram:{
		"type":1,
		"comment":"神兵铸魂10次"
	}
	
};