export const vip_advantage = {
    
    
    "0": {
        "daily_money_treeTimes": 5,
        "equip_count": 120,
        "equip_wash_times": 10,
        "daily_instance_times": 1,
        "buy_daily_instance_times": 1,
        "jjc_free_times": 5,
        "equip_instance_times": 5,
        "buy_equip_instance_times": 10,
        "instance_times": 5,
        "buy_instance_times": 5,
        "tower_sweep_times": 1,
        "tower_diamond_sweep_times": 2,
        "gest_free_refresh_times": 5,
        "gest_free_challenge_times": 3,
        "chat_color": "#fde7ca",
        "discount": 100,
        "lv_frame": null,
        "buy_exp_fb_times": 1
    },
    
    "1": {
        "daily_money_treeTimes": 8,
        "equip_count": 130,
        "equip_wash_times": 11,
        "daily_instance_times": 1,
        "buy_daily_instance_times": 2,
        "jjc_free_times": 6,
        "equip_instance_times": 5,
        "buy_equip_instance_times": 11,
        "instance_times": 5,
        "buy_instance_times": 6,
        "tower_sweep_times": 1,
        "tower_diamond_sweep_times": 3,
        "gest_free_refresh_times": 5,
        "gest_free_challenge_times": 3,
        "chat_color": "#fde7ca",
        "discount": 100,
        "lv_frame": 1,
        "buy_exp_fb_times": 3
    },
    
    "2": {
        "daily_money_treeTimes": 10,
        "equip_count": 140,
        "equip_wash_times": 12,
        "daily_instance_times": 2,
        "buy_daily_instance_times": 2,
        "jjc_free_times": 7,
        "equip_instance_times": 5,
        "buy_equip_instance_times": 12,
        "instance_times": 5,
        "buy_instance_times": 7,
        "tower_sweep_times": 1,
        "tower_diamond_sweep_times": 4,
        "gest_free_refresh_times": 5,
        "gest_free_challenge_times": 3,
        "chat_color": "#fde7ca",
        "discount": 80,
        "lv_frame": 2,
        "buy_exp_fb_times": 4
    },
    
    "3": {
        "daily_money_treeTimes": 12,
        "equip_count": 150,
        "equip_wash_times": 13,
        "daily_instance_times": 2,
        "buy_daily_instance_times": 2,
        "jjc_free_times": 8,
        "equip_instance_times": 6,
        "buy_equip_instance_times": 13,
        "instance_times": 5,
        "buy_instance_times": 8,
        "tower_sweep_times": 1,
        "tower_diamond_sweep_times": 5,
        "gest_free_refresh_times": 5,
        "gest_free_challenge_times": 3,
        "chat_color": "#fde7ca",
        "discount": 80,
        "lv_frame": 2,
        "buy_exp_fb_times": 5
    },
    
    "4": {
        "daily_money_treeTimes": 14,
        "equip_count": 160,
        "equip_wash_times": 14,
        "daily_instance_times": 2,
        "buy_daily_instance_times": 3,
        "jjc_free_times": 9,
        "equip_instance_times": 6,
        "buy_equip_instance_times": 14,
        "instance_times": 5,
        "buy_instance_times": 9,
        "tower_sweep_times": 2,
        "tower_diamond_sweep_times": 6,
        "gest_free_refresh_times": 6,
        "gest_free_challenge_times": 3,
        "chat_color": "#fde7ca",
        "discount": 80,
        "lv_frame": 2,
        "buy_exp_fb_times": 6
    },
    
    "5": {
        "daily_money_treeTimes": 16,
        "equip_count": 170,
        "equip_wash_times": 15,
        "daily_instance_times": 3,
        "buy_daily_instance_times": 3,
        "jjc_free_times": 10,
        "equip_instance_times": 7,
        "buy_equip_instance_times": 15,
        "instance_times": 5,
        "buy_instance_times": 10,
        "tower_sweep_times": 2,
        "tower_diamond_sweep_times": 7,
        "gest_free_refresh_times": 6,
        "gest_free_challenge_times": 3,
        "chat_color": "#fde7ca",
        "discount": 70,
        "lv_frame": 3,
        "buy_exp_fb_times": 8
    },
    
    "6": {
        "daily_money_treeTimes": 18,
        "equip_count": 180,
        "equip_wash_times": 16,
        "daily_instance_times": 3,
        "buy_daily_instance_times": 3,
        "jjc_free_times": 11,
        "equip_instance_times": 7,
        "buy_equip_instance_times": 16,
        "instance_times": 6,
        "buy_instance_times": 11,
        "tower_sweep_times": 2,
        "tower_diamond_sweep_times": 8,
        "gest_free_refresh_times": 6,
        "gest_free_challenge_times": 4,
        "chat_color": "#ffe380",
        "discount": 70,
        "lv_frame": 3,
        "buy_exp_fb_times": 9
    },
    
    "7": {
        "daily_money_treeTimes": 20,
        "equip_count": 200,
        "equip_wash_times": 17,
        "daily_instance_times": 3,
        "buy_daily_instance_times": 4,
        "jjc_free_times": 12,
        "equip_instance_times": 8,
        "buy_equip_instance_times": 17,
        "instance_times": 6,
        "buy_instance_times": 12,
        "tower_sweep_times": 2,
        "tower_diamond_sweep_times": 9,
        "gest_free_refresh_times": 6,
        "gest_free_challenge_times": 4,
        "chat_color": "#ffe380",
        "discount": 70,
        "lv_frame": 3,
        "buy_exp_fb_times": 10
    },
    
    "8": {
        "daily_money_treeTimes": 22,
        "equip_count": 220,
        "equip_wash_times": 18,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 4,
        "jjc_free_times": 13,
        "equip_instance_times": 8,
        "buy_equip_instance_times": 18,
        "instance_times": 6,
        "buy_instance_times": 13,
        "tower_sweep_times": 3,
        "tower_diamond_sweep_times": 10,
        "gest_free_refresh_times": 7,
        "gest_free_challenge_times": 4,
        "chat_color": "#ffe380",
        "discount": 70,
        "lv_frame": 3,
        "buy_exp_fb_times": 12
    },
    
    "9": {
        "daily_money_treeTimes": 24,
        "equip_count": 240,
        "equip_wash_times": 19,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 4,
        "jjc_free_times": 14,
        "equip_instance_times": 9,
        "buy_equip_instance_times": 19,
        "instance_times": 7,
        "buy_instance_times": 14,
        "tower_sweep_times": 3,
        "tower_diamond_sweep_times": 11,
        "gest_free_refresh_times": 7,
        "gest_free_challenge_times": 5,
        "chat_color": "#ffe380",
        "discount": 70,
        "lv_frame": 3,
        "buy_exp_fb_times": 13
    },
    
    "10": {
        "daily_money_treeTimes": 26,
        "equip_count": 260,
        "equip_wash_times": 20,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 5,
        "jjc_free_times": 15,
        "equip_instance_times": 9,
        "buy_equip_instance_times": 20,
        "instance_times": 7,
        "buy_instance_times": 15,
        "tower_sweep_times": 3,
        "tower_diamond_sweep_times": 12,
        "gest_free_refresh_times": 7,
        "gest_free_challenge_times": 5,
        "chat_color": "#ffe380",
        "discount": 60,
        "lv_frame": 4,
        "buy_exp_fb_times": 14
    },
    
    "11": {
        "daily_money_treeTimes": 28,
        "equip_count": 280,
        "equip_wash_times": 21,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 5,
        "jjc_free_times": 16,
        "equip_instance_times": 10,
        "buy_equip_instance_times": 21,
        "instance_times": 7,
        "buy_instance_times": 16,
        "tower_sweep_times": 3,
        "tower_diamond_sweep_times": 13,
        "gest_free_refresh_times": 8,
        "gest_free_challenge_times": 6,
        "chat_color": "#ffe380",
        "discount": 60,
        "lv_frame": 4,
        "buy_exp_fb_times": 15
    },
    
    "12": {
        "daily_money_treeTimes": 30,
        "equip_count": 300,
        "equip_wash_times": 22,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 5,
        "jjc_free_times": 17,
        "equip_instance_times": 10,
        "buy_equip_instance_times": 22,
        "instance_times": 7,
        "buy_instance_times": 17,
        "tower_sweep_times": 3,
        "tower_diamond_sweep_times": 14,
        "gest_free_refresh_times": 8,
        "gest_free_challenge_times": 6,
        "chat_color": "#ffe380",
        "discount": 60,
        "lv_frame": 4,
        "buy_exp_fb_times": 16
    },
    
    "13": {
        "daily_money_treeTimes": 35,
        "equip_count": 320,
        "equip_wash_times": 23,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 6,
        "jjc_free_times": 18,
        "equip_instance_times": 12,
        "buy_equip_instance_times": 23,
        "instance_times": 7,
        "buy_instance_times": 18,
        "tower_sweep_times": 4,
        "tower_diamond_sweep_times": 15,
        "gest_free_refresh_times": 8,
        "gest_free_challenge_times": 6,
        "chat_color": "#ffe380",
        "discount": 60,
        "lv_frame": 5,
        "buy_exp_fb_times": 17
    },
    
    "14": {
        "daily_money_treeTimes": 40,
        "equip_count": 340,
        "equip_wash_times": 24,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 6,
        "jjc_free_times": 19,
        "equip_instance_times": 12,
        "buy_equip_instance_times": 24,
        "instance_times": 7,
        "buy_instance_times": 19,
        "tower_sweep_times": 4,
        "tower_diamond_sweep_times": 16,
        "gest_free_refresh_times": 9,
        "gest_free_challenge_times": 6,
        "chat_color": "#ffe380",
        "discount": 60,
        "lv_frame": 5,
        "buy_exp_fb_times": 18
    },
    
    "15": {
        "daily_money_treeTimes": 50,
        "equip_count": 360,
        "equip_wash_times": 25,
        "daily_instance_times": 4,
        "buy_daily_instance_times": 6,
        "jjc_free_times": 20,
        "equip_instance_times": 15,
        "buy_equip_instance_times": 25,
        "instance_times": 7,
        "buy_instance_times": 20,
        "tower_sweep_times": 4,
        "tower_diamond_sweep_times": 17,
        "gest_free_refresh_times": 9,
        "gest_free_challenge_times": 6,
        "chat_color": "#ffe380",
        "discount": 50,
        "lv_frame": 5,
        "buy_exp_fb_times": 20
    }
}