export let tips_back = {
       "lack diamond":"元宝不足",
        "lack money":"银币不足",
        "lack material":"材料不足",
        "lack level":"等级不足",
        "lack degree" : "阶级不足",
        "equip prop set full": "背包已满，请清理背包",
        "equip prop set not enough": "背包空间不足，请清理背包",
        "revenge count limit": "复仇次数已达上限",
        "seek help count limit": "请求帮助次数已达上限",
        "other fighting": "其它玩家正在帮助中，请稍后再试！",


        "enter the name of the guild":"请输入门派名字",
        "enter the guild declaration":"请输入门派宣言",
        "leave the guild less than 24 hour":"离开门派不足24小时",
        "gang name has been used":"门派名已存在",
        "gang member too much":"门派成员已满",
        "already have gang":"已有门派",
        "repeat apply limit":"不能重复申请",
        "not have gang":"没有门派",
        "authority limit":"权限不足",
        "list is not the player":"申请列表中不存在申请人",
        "the player already have gang":"申请人已有门派",
        "gang is full":"门派成员已到上限",
        "can't appointed himself":"不能任命自己",
        "already vice_chairman":"已是副门主",
        "vice_chairman is full":"副门主人数已到上限",
        "already ordinary member":"已是普通成员",
        "president can't quit the guild":"门主不能退出门派",
        "can't kick myself out":"不能踢自己",
        "player not in the gang":"门派不存在此人",
        "can not kick out president":"不能踢门主",
        "gang level limit":"门派等级不足",
        "lack contribute":"门派贡献不足",
        "lack item":"商品已售尽",
        "guardInfo error":"关卡信息错误",
        "guard isn't belong to this instance":"关卡不属于该副本",
        "instance isn't open":"副本未开放",
        "has run out of challenges":"挑战次数已用尽",
        "fight error":"战斗异常",
        "isn't perfect pass":"不是完美通关",
        "run out of purchase times":"购买次数已用尽",
        "purchase too much":"提升VIP等级，可获得更多购买次数",
        "the position is no one":"该位置没有玩家",
        "captain can't turn to robot":"队长不能转给机器人",
        "already captain":"已经是队长",
        "is not captain":"不是队长",
        "can't kick self":"不能踢自己",
        "can't transfer to self":"不能转让队长给自己",
        "not player":"队长不能转给机器人",
        "the role level not enough":"该玩家等级不足",
        "invited players leave out":"该玩家已离线",
        "already have a team":"该玩家已有队伍",
        "person num not enough":"至少三人才可开启任务",
        "team personnel is full":"队伍已满员",

        "world boss not open":"世界Boss未开启",
        "world boss has been closed":"世界BOSS已关闭",
        "boss is dead":"世界Boss已死亡",
        "damage too much":"伤害异常,请重新进入游戏",
        "total damage limit":"总伤害限制",
        "BossAttribute config error":"BossAttribute配置错误",
        "already award":"已领奖",

        "temporarily cannot attack":"暂时不能攻击",
        "did not open activity time":"未在活动时间",
        "did not open date":"活动未在开启日期",
        "monster is dead":"怪物已死亡",
        "is not monster":"不存在怪物信息",
        "not reached conditions":"未达到领取条件",

        "partner type error":"伙伴类型错误",
        "no partner":"没有伙伴",
        "is not partner":"不是伙伴",
        "cannot exceed the max level":"不能超过最大等级",
        "partner level has reached the max":"伙伴等级达到上限",
        "lack drug":"药品不足",
        "isn't drug":"不是药品",
        "partner star is max":"伙伴星级达到上限",
        "cannot exceed the max star level":"不能超过最大星级",
        "lack prop":"物品不足",
        "skill level full":"技能等级已到上限",
        "lack skill level":"等级不足",
        "already exist partner":"需交换的伙伴已存在",
        "partners have reached a limit":"上阵伙伴数量已达到上限",
        "don't replace leading actor":"不能交换主角",
        "don't replace cultivation partner":"不能交换正在修炼的伙伴",
        "lack cultivation exp":"培养经验不足",
        "cultivation max":"已达最大突破等级",
        "index is error":"领奖位置错误",
        "no goods":"没有商品",
        "lack soul jade":"魂玉不足",
        "lack soul":"材料不足",
        "lack goods":"商品不足",
        "lack spirit":"精力不足",

        "recharge config file error":"充值配置表错误",
        "lack rmb":"钱不够",
        "robolet not yet due":"未到期",
        "robolet already get":"已领取",
        "robolet already over or not exist":"已到期或未购买",
        "vipupgradeconfig error":"vip配置表错误",

        "error params":"参数错误",
        "already used":"已使用",
        "already checked":"已签到",
        "no gem":"宝石已用完",
        "times is used up":"免费次数已用完",
        "cd":"免费次数冷却中",
        "error box":"宝箱错误",
        "is not fight time":"副本未到开放时间",
        "instance locked":"章节未解锁",
        "boss status error":"BOSS神游了",
        "boss already die or boss not unlock":"BOSS已死亡或者该BOSS未解锁",
        "dismatch equip":"装备类型错误",
        "not equipment":"这货不是装备",
        "equip already is max level":"装备已到最大等级",
        "error soul type":"元神类型不正确",
        "not soul":"该物品不是元神",
        "not leader":"您不是房主",
        "already buy":"请勿重复购买",
        "please start wild first":"您还未开始野外挂机",
        "you are attacked":"您正被攻击中",
        "rival is attacked":"敌方处于激战中,不要乘人之危",
        "rival rank is changed":"排名已经发生改变，请刷新",
        "my rank is changed":"排名已经发生改变，请刷新",
        "you can't fight with yourself":"您不能向你自己发起挑战",
        "role was online or attacked":"该玩家正在战斗中或被其他玩家攻击中",
        "the role rank is changed":"该位置对手已发生变化，请先刷新列表",
        "you can't take part in warcraft":"暂未获得争霸赛资格",
        "you can't fight with him":"您暂未获得与他挑战的资格",
        "please wait fight end":"请等待挑战结束",
        "please start fight first":"请先开始战斗",
        "pvp fight timeout":"竞技场战斗超时，已自动结束战斗",
        "lack rank":"排名不足，不能购买",
        "count limit":"购买次数已用完",
        "mission-count mismatch condition":"非法挑战BOSS",
        "already had clothes":"已拥有该时装，无法再购买",
        "boss state error":"当前宝箱无法领取",
        "time error":"当前非活动/领取时间",
        "full star, need break" : "已满星，需要突破",
        "material index error" : "材料索引错误",
        "lack wing star" : "翅膀星级错误",
        "max wing degree" : "翅膀阶级已经最大",
        "already enable" : "已经激活",
        "no skin" : "无此皮肤",
        "index err" : "错误的参数",
        "no type" : "无此类型",
        "already gain" : "已经领取",
        "not confirm condition" : "不满足条件",
        "award flag incorrect" : "领取标志位错误",
        "id err" : "无此玩家ID",
        "no name" : "无效的名字",
        "no group" : "无小队",
        "mail has been read" : "邮件已被领取",
        "emails time out" : "邮件超时",
        "pay money error" : "花费金钱错误",
        "invalid order" : "无效的订单",
        "type err" : "错误类型",
        "no treasure" : "无此神兵",
        "level up error" : "升级错误",
        "star up error" : "升星错误",
        "lack prop count" : "缺失物品数量",
        "no weapon" : "无此武器",
        "wash error, lack material" : "洗练错误，材料缺失",
        "wash error, lack money" : "洗练错误，金币缺失",
        "wash error, lack diamond" : "洗练错误，钻石缺失",
        "type limit" : "类型受限",
        "lock too much" : "不能锁",
        "error status" : "状态错误",
        "lack count" : "次数不足",
        "lack score" : "积分不足",
        "ready err status" : "准备状态错误",
        "fight err status" : "战斗状态错误",
        "no robot" : "无此机器人",
        "need pass this chapter" : "需要通关本章节",
        "already fight" : "已经通关",
        "no_boss" : "无此boss",
        "need pass previous instance" : "需要通关上一关卡",
        "sweep limit" : "未达到扫荡条件",
        "mission limit" : "普通关卡限制",
        "level limit" : "等级限制",
        "match errror" : "匹配错误",
        "lack damage" : "伤害不足",
        "need refresh" : "需要刷新",
        "need relive" : "需要复活",
        "lack coin" : "兑换值不足",
        "not pass previous mission" : "需要通关上一关卡",
        "invaild chapter" : "无效的章节",
        "length limit" : "长度限制",
        "repeat name" : "重复的名字",
        "forbid substr" : "无效的字符",
        "limit char range" : "字符限制",
        "no more spirit value" : "精力不足",
        "no gang" : "没有门派",
        "no suit gang": "没有合适门派",
        "chip not enough":"碎片不足",
        "phone number has bind":"该手机号已被绑定",
        "verification code is not valid":"验证码无效",

        "not share wx":"未分享微信",
        "this week has been share award":"本周已领微信奖励",

        "please input cdkey":"请输入兑换码",
        "cdkey error":"兑换码错误",
        "cdkey useless":"无效兑换码",
        "cdkey has expired":"兑换码已过期",
        "cdkey has been used":"该兑换码已被使用",
        "have been using the same type cdkey":"已领取过同类活动礼包",

        "activity is close":"活动结束或你未达到参与条件",
        "award time over":"领奖时间已截止",
        "award already max":"领奖次数已达上限",
        "activity not open":"活动未开启",
		"lack tab":"未找到对应数据",
		"sale time over":"该轮活动已结束",

        "twoNot_equal":"两次输入的密码不一致",
        "pw_short":"密码太短！",
        "name_short":"账号太短！",
        "name_long":"账号太长！",
        "name_illegal":"账号只能由英文数字组成！",
        "pw_long":"密码太长！",
        "phone number has existed":"已注册！返回首页直接登陆",
        "user not exist":"账号不存在",
        "phone number not found":"账号不存在，不能重置",
        "invalid password":"无效密码",
        "user already exists":"该账号已注册,返回直接登录!!",
        "phoneRight_num":"请输入正确的手机号码！",
        "user didn't register":"很遗憾，您没有绑定手机号,无法找回！",
        "not_agree":"请同意“一世之尊”的相关条款",

        "not manager":"不是门派管理人员",
        "already apply":"已申请",
        "not enough gang level":"门派等级不足3级",
        "apply time is over":"匹配时间已结束",
        "not attend gang war":"无法参与公会战",
        "gang war bye":"本次门派战轮空",
        "temporarily unable entry":"暂时不能进入",
        "enough person":"人数已达上限",
        "no buff":"增益已被他人拾取",

        "no target":"没找到释放目标",
        "fight status err":"战斗状态错误",
        "no award count":"今日已无奖励次数",
        "in group":"今日已无奖励次数",
        "someone not ready":"有队员未装备",
        "fighting":"正在战斗",
        "has player is fighting":"有队员正战斗中",
        "team dismiss":"队伍已解散",
        "aready buy buff":"已购买",
        

        "wxpay return error" : "调取微信支付失败!",
        "not found openid" : "未获得微信授权！",

        "timeout":"通讯超时，请稍后再试！"
    };