export default {
    "eff_rolef_skill2_1": ["eff_rolef_skill2_1"],
    "eff_rolef_skill1_1": ["eff_rolef_skill1_1"],
    "eff_role7_skill3_1": ["eff_role7_skill3_1"],
    "eff_role7_skill3_2": ["eff_role7_skill3_2"],
    "eff_body_buff05": ["eff_body_buff05"],
    "eff_role12_skill2_2": ["eff_role12_skill2_2"],
    "eff_role12_skill2_1": ["eff_role12_skill2_1"],
    "eff_sce_dianji": ["eff_sce_dianji"],
    "eff_common_skill1_2": ["eff_common_skill1_2"],
    "eff_monster01_skill1_1": ["eff_monster01_skill1_1"],
    "eff_monster01_skill2_1": ["eff_monster01_skill2_1"],
    "eff_monster03_skill1_1": ["eff_monster03_skill1_1"],
    "eff_monster03_skill2_1": ["eff_monster03_skill2_1"],
    "eff_monster23_skill1_1": ["eff_monster23_skill1_1"],
    "eff_monster23_skill2_1": ["eff_monster23_skill2_1"],
    "eff_monster27_skill1_1": ["eff_monster27_skill1_1"],
    "eff_monster27_skill2_1": ["eff_monster27_skill2_1"],
    "eff_role8_skill1_1": ["eff_role8_skill1_1"],
    "eff_role8_skill2_1": ["eff_role8_skill2_1"],
    "eff_role3_skill2_1" : ["eff_role3_skill2_1"],
    "eff_role3_skill2_2" : ["eff_role3_skill2_2"],
    "eff_ui_rwwc02":["eff_ui_rwwc02"],
    "eff_rwcstx01":["eff_rwcstx01"],
    "eff_rwcstx02":["eff_rwcstx02"],
    "eff_treasure_attack1_1":["eff_treasure_attack1_1"],
    "eff_treasure_attack1_2":["eff_treasure_attack1_2"],
    "eff_treasure_attack1_3":["eff_treasure_attack1_3"],
    "eff_treasure_attack2_1":["eff_treasure_attack2_1"],
    "eff_treasure_attack2_2":["eff_treasure_attack2_2"],
    "eff_treasure_attack2_3":["eff_treasure_attack2_3"],
    "eff_treasure_attack3_1":["eff_treasure_attack3_1"],
    "eff_treasure_attack3_2":["eff_treasure_attack3_2"],
    "eff_treasure_attack3_3":["eff_treasure_attack3_3"],
    "eff_ui_huobanshengji":["eff_ui_huobanshengji"],
    "eff_rolem_sk1":["eff_rolem_sk1"],
    "eff_rolem_sk2":["eff_rolem_sk2"],
    "eff_rolem_sk3":["eff_rolem_sk3"],
    "eff_rolem_sk4":["eff_rolem_sk4"],
    "eff_rolem_sk5":["eff_rolem_sk5"],
    "eff_rolef_sk1":["eff_rolef_sk1"],
    "eff_rolef_sk2":["eff_rolef_sk2"],
    "eff_rolef_sk3":["eff_rolef_sk3"],
    "eff_rolef_sk4":["eff_rolef_sk4"],
    "eff_rolef_sk5":["eff_rolef_sk5"],
    "eff_hit_rolem_sk2":["eff_hit_rolem_sk2"],
    "eff_rolem_attack":["eff_rolem_attack"],
    "eff_rolef_attack":["eff_rolef_attack"],
    "eff_hit_rolef_common":["eff_hit_rolef_common"],
    "eff_hit_rolem_common":["eff_hit_rolem_common"],
    "eff_ui_yaoqianshu01":["eff_ui_yaoqianshu02","eff_ui_yaoqianshu01"],
    "eff_boss01_sk1":["eff_boss01_sk1"],
    "eff_selected01":["eff_selected01"],
    "eff_rolef_show":["eff_rolef_show"],
    "eff_rolem_show":["eff_rolem_show"],
    "eff_hit_godweapon_rolem01":["eff_hit_godweapon_rolem01"],
    "eff_hit_godweapon_rolem02":["eff_hit_godweapon_rolem02"],
    "eff_hit_godweapon_rolem03":["eff_hit_godweapon_rolem03"],
    "eff_hit_godweapon_rolef01":["eff_hit_godweapon_rolef01"],
    "eff_hit_godweapon_rolef02":["eff_hit_godweapon_rolef02"],
    "eff_hit_godweapon_rolef03":["eff_hit_godweapon_rolef03"],
    "eff_godweapon_rolef01":["eff_godweapon_rolef01"],"eff_godweapon_rolef02":["eff_godweapon_rolef02"],"eff_godweapon_rolef03":["eff_godweapon_rolef03"],"eff_godweapon_rolem01":["eff_godweapon_rolem01"],"eff_godweapon_rolem02":["eff_godweapon_rolem02"],"eff_godweapon_rolem03":["eff_godweapon_rolem03"],
    "eff_scexzjs01":["eff_scexzjs01"],
    "eff_scexzjs02":["eff_scexzjs02"],
    "test_dlwp01":["test_dlwp01"],
    "test_dlwp02":["test_dlwp02"],
    "test_dlwp03":["test_dlwp03"],
    "test_dlwp04":["test_dlwp04"],
    "test_dlwp05":["test_dlwp05"],
    "eff_ui_fuling_fengling_1":["eff_ui_fuling_fengling_1"],
    "eff_ui_fuling_fengling_2":["eff_ui_fuling_fengling_2"],
    "eff_ui_fuling_huoling_1":["eff_ui_fuling_huoling_1"],
    "eff_ui_fuling_huoling_2":["eff_ui_fuling_huoling_2"],
    "eff_ui_fuling_leiling_1":["eff_ui_fuling_leiling_1"],
    "eff_ui_fuling_leiling_2":["eff_ui_fuling_leiling_2"],
    "eff_ui_fuling_shuiling_1":["eff_ui_fuling_shuiling_1"],
    "eff_ui_fuling_shuiling_2":["eff_ui_fuling_shuiling_2"],
    "eff_ui_fuling_xuanzhong":["eff_ui_fuling_xuanzhong"],
    "eff_ui_cuilian_xishou":["eff_ui_cuilian_xishou"],
    "eff_ui_cuilian_dianliang":["eff_ui_cuilian_dianliang"],
    "eff_ui_zhuhun_bianan1":["eff_ui_zhuhun_bianan1"],
    "eff_ui_zhuhun_bianan2":["eff_ui_zhuhun_bianan2"],
    "eff_ui_zhuhun_bianan3":["eff_ui_zhuhun_bianan3"],
    "eff_ui_zhuhun_bianan4":["eff_ui_zhuhun_bianan4"],
    "eff_ui_zhuhun_bianan5":["eff_ui_zhuhun_bianan5"],
    "eff_ui_zhuhun_bianan6":["eff_ui_zhuhun_bianan6"],
    "eff_ui_zhuhun_bianan7":["eff_ui_zhuhun_bianan7"],
    "eff_ui_zhuhun_bianan8":["eff_ui_zhuhun_bianan8"],
    "eff_ui_zhuhun_dianliang1":["eff_ui_zhuhun_dianliang1"],
    "eff_ui_zhuhun_dianliang2":["eff_ui_zhuhun_dianliang2"],
    "eff_ui_zhuhun_dianliang3":["eff_ui_zhuhun_dianliang3"],
    "eff_ui_zhuhun_dianliang4":["eff_ui_zhuhun_dianliang4"],
    "eff_ui_zhuhun_dianliang5":["eff_ui_zhuhun_dianliang5"],
    "eff_ui_zhuhun_dianliang6":["eff_ui_zhuhun_dianliang6"],
    "eff_ui_zhuhun_dianliang7":["eff_ui_zhuhun_dianliang7"],
    "eff_ui_zhuhun_dianliang8":["eff_ui_zhuhun_dianliang8"],
    "eff_ui_zhuhun_xunhuan1":["eff_ui_zhuhun_xunhuan1"],
    "eff_ui_zhuhun_xunhuan2":["eff_ui_zhuhun_xunhuan2"],
    "eff_ui_zhuhun_xunhuan3":["eff_ui_zhuhun_xunhuan3"],
    "eff_ui_zhuhun_xunhuan4":["eff_ui_zhuhun_xunhuan4"],
    "eff_ui_zhuhun_xunhuan5":["eff_ui_zhuhun_xunhuan5"],
    "eff_ui_zhuhun_xunhuan6":["eff_ui_zhuhun_xunhuan6"],
    "eff_ui_zhuhun_xunhuan7":["eff_ui_zhuhun_xunhuan7"],
    "eff_ui_zhuhun_xunhuan8":["eff_ui_zhuhun_xunhuan8"],
    "model_ui_stan1":["model_ui_stan1"],
    "model_ui_stan2":["model_ui_stan2"],
    "model_ui_stan3":["model_ui_stan3"],
    "model_ui_stan4":["model_ui_stan4"],
    "model_ui_stan5":["model_ui_stan5"],
    "model_ui_stan6":["model_ui_stan6"],
    "model_ui_stan7":["model_ui_stan7"],
    "model_ui_stan8":["model_ui_stan8"],
    "model_ui_stanaa1":["model_ui_stanaa1"],
    "model_ui_stanaa2":["model_ui_stanaa2"],
    "model_ui_stanaa3":["model_ui_stanaa3"],
    "model_ui_stanaa4":["model_ui_stanaa4"],
    "model_ui_stanaa5":["model_ui_stanaa5"],
    "model_ui_stanaa6":["model_ui_stanaa6"],
    "model_ui_stanaa7":["model_ui_stanaa7"],
    "model_ui_stanaa8":["model_ui_stanaa8"],
    "model_ui_stangg1":["model_ui_stangg1"],
    "model_ui_stangg2":["model_ui_stangg2"],
    "model_ui_stangg3":["model_ui_stangg3"],
    "model_ui_stangg4":["model_ui_stangg4"],
    "model_ui_stangg5":["model_ui_stangg5"],
    "model_ui_stangg6":["model_ui_stangg6"],
    "model_ui_stangg7":["model_ui_stangg7"],
    "model_ui_stangg8":["model_ui_stangg8"],
    "eff_hit_roleg_common":["eff_hit_roleg_common"],
    "eff_roleg_attack":["eff_roleg_attack"],
    "eff_roleg_sk1":["eff_roleg_sk1"],
    "eff_roleg_sk2":["eff_roleg_sk2"],
    "eff_godweapon_roleg01":["eff_godweapon_roleg01"],
    "eff_godweapon_roleg02":["eff_godweapon_roleg02"],
    "eff_godweapon_roleg03":["eff_godweapon_roleg03"],
    "eff_hit_godweapon_roleg01":["eff_hit_godweapon_roleg01"],"eff_hit_godweapon_roleg02":["eff_hit_godweapon_roleg02"],"eff_hit_godweapon_roleg03":["eff_hit_godweapon_roleg03"],
    "eff_roleg_sk4":["eff_roleg_sk4"],
    "eff_roleg_sk3":["eff_roleg_sk3"],
    "eff_hit_roleg_sk4":["eff_hit_roleg_sk4"],
    "eff_roleg_sk5":["eff_roleg_sk5"],
    "eff_roleg_show":["eff_roleg_show"],
    "model_dl_zhuangbei":["model_dl_zhuangbei"],
    "eff_hit_monster_common":["eff_hit_monster_common"],
    "eff_boss02_sk1":["eff_boss02_sk1"],
    "eff_boss03_sk1":["eff_boss03_sk1"],
    "eff_boss03_sk2":["eff_boss03_sk2"],
    "eff_boss04_sk1":["eff_boss04_sk1"],
    "eff_boss04_sk2":["eff_boss04_sk2"],
    "eff_boss05_sk1":["eff_boss05_sk1"],
    "eff_boss06_sk1":["eff_boss03_sk2"],
    "eff_boss07_sk1":["eff_boss07_sk1"],
    "model_dl_baoshi":["model_dl_baoshi"],
    "model_dl_baoxiang":["model_dl_baoxiang"],
    "model_dl_daizi":["model_dl_daizi"],
    "model_dl_jiezhi":["model_dl_jiezhi"],
    "model_dl_juanzhou":["model_dl_juanzhou"],
    "model_dl_shitou":["model_dl_shitou"],
    "model_dl_yifu":["model_dl_zhuangbei"],
    "model_dl_qiang":["model_dl_qiang"],
    "model_dl_dao":["model_dl_dao"],
    "model_dl_chui":["model_dl_chui"],
    "model_dl_changxue":["model_dl_changxue"],
    "model_dl_hujian":["model_dl_hujian"],
    "model_dl_hutui":["model_dl_hutui"],
    "model_dl_huwan":["model_dl_huwan"],
    "model_dl_shouzhuo":["model_dl_shouzhuo"],
    "model_dl_toukui":["model_dl_toukui"],
    "model_dl_xianglian":["model_dl_xianglian"],
    "eff_ui_fuling_shengji":["eff_ui_fuling_shengji"],
    "eff_ui_fuling_jinjie":["eff_ui_fuling_jinjie"],
    "eff_ui_longhun_bianse":["eff_ui_longhun_bianse"],
    "eff_ui_longhun_cheng":["eff_ui_longhun_cheng"],
    "eff_ui_longhun_shengji":["eff_ui_longhun_shengji"],
    "eff_ui_longhun_zi":["eff_ui_longhun_zi"],
    "eff_ui_longhun_lan":["eff_ui_longhun_lan"],
    "eff_ui_chongwu_jinjie":["eff_ui_chongwu_jinjie"]
}