export default {
    "model_weapon_rolef": {
        "res": ["Fe1YQbm4xBJieW6Pahrte2.geo", "WjGxgBri4TSAnUQsE6W2Vw.jpg"],
        "aniControl": "",
        "tpl": "4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones": [],
        "bounds": [],
        "rootbone": null
    },
    "model_weapon_rolef06":{
        "res":["j8h2tPXRUML2mi4vqd4Kt.geo","X5snAgsEV4LAFLrarAhjXD.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_rolef06"],
        "aniBoxs":[]
    },
    "model_weapon_role1":{
        "res":["RcUMpxZyUittHwmVN2BP4n.geo","DU41hzS2eDndSD1goyjasJ.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_roleg01":{
        "res":["5QtFAXU8TxGbnfzvfLsRK1.geo","RU7RvMJVhuU2BcMyHPQFCA.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_roleg01"],
        "aniBoxs":[]
    },
    "model_weapon_roleg02":{
        "res":["LPt6NZtSdgJKFhyaP22uBt.geo","EFBmdqKUCCBBQFHeVyaHSM.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_roleg02"],
        "aniBoxs":[]
    },
    "model_weapon_roleg03":{
        "res":["G3YY3Y8RUqcyBsqpqyrkKo.geo","5XTFVBMigZUhwJn8ehE6eG.jpg"],
        "aniControl":"",
        "tpl":"FBWnaUSV85M5vwSoeuUdum.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_roleg03"],
        "aniBoxs":[]
    },
    "model_weapon_roleg04":{
        "res":["XTiCnuzGqy2PVyAUry4P36.geo","E8nFAMBH1KvRw25oP7ANwN.jpg"],
        "aniControl":"",
        "tpl":"FBWnaUSV85M5vwSoeuUdum.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_roleg04"],
        "aniBoxs":[]
    },
    "model_weapon_roleg05":{
        "res":["Rx3YHZXyW43Q55VXGay5Px.geo","WkavPq9MT1Zyomdtp5Zbyn.jpg"],
        "aniControl":"",
        "tpl":"FBWnaUSV85M5vwSoeuUdum.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_roleg05"],
        "aniBoxs":[]
    },
    "model_weapon_roleg06":{
        "res":["WhNm4XCR9Ve293xPoi1vbj.geo","xmkC1UhA4iwzxzgttkvUn.jpg"],
        "aniControl":"",
        "tpl":"FBWnaUSV85M5vwSoeuUdum.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_roleg06"],
        "aniBoxs":[]
    },
    "model_rolef02weapon":{
        "res":["S6DAugYiedFWJyoTJckQSD.geo","QPGaFwWZUQynsk3D55dVYZ.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_rolef02weapon"],
        "aniBoxs":[]
    },
    "model_roleg02weapon":{
        "res":["NLi4de2iAjnik7fCptbftD.geo","UNLa37gdLrPqEauViB9oJM.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_roleg02weapon"],
        "aniBoxs":[]
    },
    "model_rolem02weapon":{
        "res":["22MdWRbHYTnizYPZ3h3VvY.geo","3FeYo9Du8hb1BRL8sqdCtD.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_rolem02weapon"],
        "aniBoxs":[]
    },
    "model_weapon_role8":{
        "res":["HYYpvUdqKB7qh6JCks78er.geo","6zGSnRs2hMkuWhGR2TWxiE.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_monster01_weapon01":{
        "res":["7y3JirxY6cR5z7dv1dFXvF.geo","6Nooh3zbtVy6Z5ZhAbwmSa.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_monster01_weapon01"],"aniBoxs":[]
    },
    "model_monster02":{
        "res":["KqGuDdQXF9Y5jy7gboj3xq.jpg","GkcMUMxx7DthJ9GF9TJrkH.geo","xVe5EkkHNXvA3hQVhA3ub.skl"],
        "aniControl":"model_monster02",
        "tpl":"QSNcTENPskVGc5Z36XkWWY.rtpl",
        "bones":[[2,1,3,11,13,15,14,4,31,5,16,17,20,18,19,21,24,23,7,8,9,25,22,32,26,27,28,30,29]],
        "bounds":[[[0.943914175033569,0.860268652439117,1.38650298118591],[-1.77163863182068,-0.804691910743713,-1.38650262355804]]],"rootbone":"Bip001 Pelvis",
        "names":["model_monster02","Bip001","Bip001 Footsteps","Bip001 Pelvis","Bip001 Spine","Bip001 L Thigh","Bip001 L Calf","Bip001 L Foot","Bip001 L Toe0","Bip001 L Toe0Nub","Bip001 R Thigh","Bip001 R Calf","Bip001 R Foot","Bip001 R Toe0","Bip001 R Toe0Nub","Bip001 Spine1","Bip001 Neck","Bip001 Head","Bip001 HeadNub","Bip001 L Clavicle","Bip001 L UpperArm","Bip001 L Forearm","Bip001 L Hand","Bip001 L Finger0","Bip001 L Finger01","Bip001 L Finger0Nub","Bip001 L Finger1","Bip001 L Finger11","Bip001 L Finger1Nub","Bone003","Bip001 R Clavicle","Bip001 R UpperArm","Bip001 R Forearm","Bip001 R Hand","Bip001 R Finger0","Bip001 R Finger01","Bip001 R Finger0Nub","Bip001 R Finger1","Bip001 R Finger11","Bip001 R Finger1Nub","Bone001","Bone002"],
        "aniBoxs":[
            {"act_monster02_die":{"center":[0.0,0.0,0.0],"size":[1.0,1.0,1.0]}},{"act_monster02_diefly":{"center":[0.0,0.0,0.0],"size":[1.0,1.0,1.0]}},{"act_monster02_run":{"center":[0.0,0.0,0.0],"size":[1.0,1.0,1.0]}},{"act_monster02_skill1_1":{"center":[0.0,0.0,0.0],"size":[1.0,1.0,1.0]}},{"act_monster02_standby":{"center":[0.0,0.0,0.0],"size":[1.0,1.0,1.0]}}
        ]
    },
    "model_monster03_weapon01":{
        "res":["BzY5EEgTVVyWoS2WpDuwWK.geo","HZdihjfwhLuFeioCAKThXL.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_monster03_weapon01"],
        "aniBoxs":[]
    },
    "model_monster07_weapon01":{
        "res":["CZkPANHethnBBUQ2MtoZSx.geo","8avt2qvknVoAqE6vxYFnnM.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_monster07_weapon01"],
        "aniBoxs":[]
    },
    "model_monster08_weapon01":{
        "res":["E2irmhSgB5NVvHZPTKcUMw.geo","8avt2qvknVoAqE6vxYFnnM.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_monster08_weapon01"],
        "aniBoxs":[]
    },
    "model_monster09_weapon01":{
        "res":["59B3fHej2dfeGyqt9qUKN4.geo","8avt2qvknVoAqE6vxYFnnM.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_monster09_weapon01"],
        "aniBoxs":[]
    },
    "model_weapon_rolem01":{
        "res":["TPYZnKkmU8hzm9dRQJenR1.geo","PRq9XZFCwS5rSFkhQitSSk.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolem02":{
        "res":["PgwUU4yz2Xpr8EbBT7Rf73.geo","N6G443TgY2MAqjVtoe4UWS.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolem03":{
        "res":["Kw5MZtKjLigQv3CdKk1Q1v.geo","DvbApQqXQybe8JHPSkGyqR.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolem04":{
        "res":["MKWQQAtL5GMAno7iJm9sUs.geo","SgkQsUkU8fubpkeLnpxVi1.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolem05":{
        "res":["HMqU3U9vWpaeMMdhL8MqhH.geo","2hrNkerPva26tCBmDe9XYf.jpg"],
        "aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null,
        "names":["model_weapon_rolem05"],
        "aniBoxs":[]
    },
    "model_weapon_rolem06":{
        "res":["NLLWHqBMBxNmgmEEDt8HkU.geo","GQGTRDYet8emQa5srQBsou.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolef01":{
        "res":["ApFnHvrpPTCR5cxNYRZaxE.geo","GVDAfc4DStV4sjDd6nY8QE.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolef02":{
        "res":["ECeMgAHfwCXjri9JURv18H.geo","DnY6jE5G5154chEk64ySrq.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolef03":{
        "res":["NVUgStVz5XQwwUg4cBEXfS.geo","77EkrQ6ZWrxdarqdUkLXvK.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolef04":{
        "res":["VoFfDBmrBZkrsiTBfFquYM.geo","UNEbpqwQAfVCcdCVWmLqz7.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "model_weapon_rolef05":{
        "res":["VJjCjibDghHq9d83y3Esrn.geo","QgEUmbLgpvWBppFe7qQ7Ps.jpg"],"aniControl":"",
        "tpl":"4qJN45SeRNyZDzS7Atv9i2.rtpl",
        "bones":[],
        "bounds":[],
        "rootbone":null
    },
    "ainMod": {}
}